version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres:16.2
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - keycloak_network
    restart: unless-stopped

  keycloak:
    container_name: container-keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    hostname: keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    environment:
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/test_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: root
    command:
      - start-dev
      - --import-realm
    networks:
      - keycloak_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
